# -*- coding: utf-8 -*-
"""Atividade Luciana 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16qODFVW9aWdh0OG59xz5rSW2wD5tSOOT
"""

import pandas as pd

"""1- Ler a base de dados usando pandas."""

df=pd.read_csv("https://raw.githubusercontent.com/profzappa/profGit/refs/heads/master/netflix_titles.csv")

"""2- Exibir as 5 primeiras linhas da base."""

df.head()

"""3- Verificar informações gerais da base (colunas, tipos, valores nulos)."""

df.info()

"""4- Gerar estatísticas descritivas das variáveis numéricas."""

df.describe()

""" 5- Exibir o número de linhas e colunas da base."""

df.shape

"""6- Listar os nomes das colunas."""

df.columns

""" 7- Traduzir os nomes das colunas para português Brasil."""

df.columns = [
    'id_do_programa', 'tipo', 'titulo', 'diretor', 'elenco', 'pais',
    'data_adicao', 'ano_lancamento', 'classificacao', 'duracao', 'listado_em', 'descricao'
]
print("Colunas renomeadas com sucesso para:")
print(df.columns)

"""9- Identificar a quantidade de Filmes e Séries na base."""

df['tipo'].value_counts()

"""10- Mostrar os 10 países mais frequentes na amostra."""

df['pais'].value_counts(10)

"""11- Verificar qual é a classificação indicativa mais comum."""

df['classificacao'].value_counts()

""" 12- Listar os 10 gêneros mais recorrentes."""

df['listado_em'].value_counts()

""" 13- Resumir as informações das variáveis categóricas."""

print("Resumo das Variáveis Categóricas:\n")

for col in df.select_dtypes(include='object').columns:
    print(f"Variável: {col}")
    print(f"  - Número de valores únicos: {df[col].nunique()}")
    print(f"  - Valor mais frequente: {df[col].mode()[0] if not df[col].mode().empty else 'N/A'}")
    print(f"  - Contagem do valor mais frequente: {df[col].value_counts().max() if not df[col].value_counts().empty else 'N/A'}")
    print(f"  - Percentual de valores ausentes: {df[col].isnull().sum() / len(df) * 100:.2f}%\n")

"""Questões que podem ser respondidas a partir desta análise:

• Há mais filmes ou séries na Netflix? Mais filmes

• Qual o país que mais aparece na base? Estados Unidos

• Qual é a classificação indicativa mais comum? TV-MA

• Quais são os gêneros mais frequentes? Dramas, Filmes Internacionais
"""